# Generated by Django 5.2 on 2025-05-08 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_model', models.CharField(choices=[('llama-3.3-70b-versatile', 'Llama 3.3 70B'), ('deepseek-r1-distill-llama-70b', 'Deepseek R1 Distill Llama 70B'), ('qwen-qwq-32b', 'Qwen QWQ 32B')], default='llama-3.3-70b-versatile', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
