# Generated by Django 5.2 on 2025-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='max_tokens',
            field=models.IntegerField(default=4096),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='stream',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='temperature',
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_model',
            field=models.CharField(choices=[('llama-3.1-8b-instant', 'Llama 3.1 8B Instant'), ('llama3-8b-8192', 'Llama 3 8B'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B')], default='llama-3.1-8b-instant', max_length=50),
        ),
    ]
