# Generated by Django 5.2 on 2025-05-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userpreference_max_tokens_userpreference_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='custom_system_prompt',
            field=models.TextField(blank=True, help_text='Define how the AI assistant should behave. Leave empty to use the default prompt.', null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='use_custom_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
