# Generated by Django 5.2 on 2025-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userpreference_custom_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='cached_site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='site_name_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
